language: go

go:
  - 1.6

# Required for coverage.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as jonlawlor, then we have access to the coveralls api key, so we can run coverage as well.
script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d *.go) <("")
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash -c "${TRAVIS_BUILD_DIR}/.travis/test-coverage.sh"; fi
